try :
    print(x)
except :
    print("exception happend")
finally :
    print("try nd Except block ended")